[project]
name = "exseas_explorer"
version = "0.1.0"
description = "Web application displaying areas associated with extreme weather events"
authors = [{name = "Roman Attinger"}]
license = "MIT"
requires-python = ">=3.12, <3.13"

dependencies = [
  "click >=8.5.0",
  "dash >=4.4.1",
  "dash-ag-grid >=35.3.0",
  "dash-bootstrap-components >=2.0.4",
  "dash-extensions >=2.0.6",
  "dash-leaflet >=1.1.3",
  "flask >=3.1.2",
  "geojson >=3.3.0",
  "geopandas >=1.1.4",
  "matplotlib >=3.11.1",
  "netCDF4 >=1.7.4",
  "numpy >=2.5.2",
  "pandas >=3.0.5",
  "pyogrio >=0.13.0",
  "pyproj >=3.7.2",
  "rasterio >=1.5.1",
  "shapely >=2.1.2",
  "xarray >=2026.7.0",
]

[tool.poetry.group.dev.dependencies]
black = "^26.5.1"
ipykernel = "^7.3.0"
mypy = "^2.3.1"
pandas-stubs = "^3.0.5.260730"
pytest = "^9.1.1"
pytest-cov = "^7.1.0"
ruff = "^0.16.5"

[build-system]
requires = ["poetry-core>=2.2", "setuptools>=42"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
files = "exseas_explorer"

show_error_codes = true
allow_redefinition = true
show_error_context = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "dash_ag_grid.*",
  "dash_bootstrap_components.*",
  "dash_extensions.*",
  "dash_leaflet.*",
  "dash.*",
  "geojson.*",
  "geopandas.*",
  "matplotlib.*",
  "pytest.*",
  "rasterio.*",
  "shapely.*",
]

[tool.ruff]

[tool.ruff.lint]
# E402: module level import not at top of file
# E501: line too long - let the formatter worry about this
# E731: do not assign a lambda expression, use a def
ignore = [
  "E402",
  "E501",
  "E731",
]
select = [
  "E", # Pycodestyle
  "F", # Pyflakes
  "I", # isort
  "TID",  # flake8-tidy-imports (absolute imports),
  "UP", # Pyupgrade
  "W", # warnings
]

[tool.ruff.lint.isort]
known-first-party = ["exseas_explorer"]
